name: Go CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -count=1 ./...
      - name: Lint
        uses: golangci/golangci-lint-action@v9.3.0
        with:
          version: latest
